"""
__name__ =      Constants.py
__author__ =    "Charlemagne Marc"
__copyright__ = "Copyright 2025, ESI SWIR Project"
__credits__ =   ["Charlemagne Marc"]
__version__ =   "1.6.5"
__maintainer__ ="Charlemagne Marc"
__email__ =     "chamrc1@umbc.edu"
__status__ =    "Production"
"""

import datetime as dt

#----------------------------------------------------------------------------
#-- CONSTANTS
#----------------------------------------------------------------------------

#-- Version of SWIR_L1AGen package (adapted from HARP2_L1AGen)
VERSION = '1.5.5'  # Updated 2026-01-22

#-- Time epoch constants
EPOCH_TAI = dt.datetime(year=1970, month=1, day=1)  # For AirHARP2, use UNIX epoch
EPOCH_UNIX = dt.datetime(year=1970, month=1, day=1)
TAI2UTC = 0  # For AirHARP2, no leap second offset

#-- Fill values for NetCDF4 variables
FILL_39 = -999.
FILL_R8 = -9999999.
FILL_R4 = -9999999.
FILL_I4 = -9999999
FILL_I2 = 32767
FILL_U2 = 65535
FILL_STR = ''

#----------------------------------------------------------------------------
#-- NETCDF4/NC PROCESSOR CONSTANTS
#----------------------------------------------------------------------------

NC_FORMAT = "NETCDF4"
NC_SOURCE = "Generated by SWIR_NC_Processor.py"
SWIR_L1A_GEN_VERSION = "1.0"

INT_TIME_US_TO_MS = 1000.0

# Image dimensions and filter definitions
IMG_LINES = 1024
IMG_PIXELS = 1280
IMG_SENSORS = 1
SWIR_NUM_FILTERS = 5
SWIR_FILTER_POSITIONS = [0, 1, 2, 3, 4]
SWIR_FILTER_DESCRIPTIONS_LONG = [
    "dark",
    "1.57 um filter",
    "1.55 um filter",
    "1.38 um filter",
    "open",
]
SWIR_FILTER_LABELS = ["dark", "1.57μm", "1.55μm", "1.38μm", "open"]
SWIR_FILTER_WAVELENGTHS_UM = [0.0, 1.57, 1.55, 1.38, 999.0]

# Image variable defaults and limits
NC_FILL_VALUE = -999999
NC_SENSOR_FILL_U2 = FILL_U2
SENSOR_BITDEPTH = 14
SENSOR_VALID_MIN = 0
SENSOR_VALID_MAX = 16383
SENSOR_SCALE_FACTOR = 1.0
SENSOR_ADD_OFFSET = 0.0
SENSOR_TEMPERATURE_VALID_MIN = -50.0
SENSOR_TEMPERATURE_VALID_MAX = 60.0
INTEGRATION_TIME_VALID_MIN = 1.0
INTEGRATION_TIME_VALID_MAX = 1000.0
IMG_DIMENSIONS_INFO = f"frames(unlimited), lines({IMG_LINES}), pixels({IMG_PIXELS})"

DEFAULT_BINNING_CROSS_TRACK = 0
DEFAULT_ACQUISITION_TYPE = 1
DEFAULT_IMAGE_TYPE = 0

# Navigation data dimensions and limits
NAV_QUATERNION_ELEMENTS = 4
NAV_VECTOR_ELEMENTS = 3
NAV_ATT_TIME_VALID_MIN = 0.0
NAV_ATT_TIME_VALID_MAX = 86400.999999
NAV_ATT_QUAT_VALID_MIN = -1.0
NAV_ATT_QUAT_VALID_MAX = 1.0
NAV_ATT_RATE_VALID_MIN = -0.004
NAV_ATT_RATE_VALID_MAX = 0.004
NAV_ATT_EULER_VALID_MIN = -360.0
NAV_ATT_EULER_VALID_MAX = 360.0
NAV_ORB_POS_VALID_MIN = -7200000.0
NAV_ORB_POS_VALID_MAX = 7200000.0
NAV_ORB_VEL_VALID_MIN = -7600.0
NAV_ORB_VEL_VALID_MAX = 7600.0
NAV_ORB_LON_VALID_MIN = -180.0
NAV_ORB_LON_VALID_MAX = 180.0
NAV_ORB_LAT_VALID_MIN = -90.0
NAV_ORB_LAT_VALID_MAX = 90.0
NAV_ORB_ALT_VALID_MIN = -1000.0
NAV_ORB_ALT_VALID_MAX = 50000.0

ER2_VECTOR_ELEMENTS = 3
ER2_ORB_TIME_VALID_MIN = NAV_ATT_TIME_VALID_MIN
ER2_ORB_TIME_VALID_MAX = NAV_ATT_TIME_VALID_MAX
ER2_ORB_LON_VALID_MIN = NAV_ORB_LON_VALID_MIN
ER2_ORB_LON_VALID_MAX = NAV_ORB_LON_VALID_MAX
ER2_ORB_LAT_VALID_MIN = NAV_ORB_LAT_VALID_MIN
ER2_ORB_LAT_VALID_MAX = NAV_ORB_LAT_VALID_MAX
ER2_ORB_ALT_VALID_MIN = NAV_ORB_ALT_VALID_MIN
ER2_ORB_ALT_VALID_MAX = NAV_ORB_ALT_VALID_MAX
ER2_ATT_EULER_VALID_MIN = NAV_ATT_EULER_VALID_MIN
ER2_ATT_EULER_VALID_MAX = NAV_ATT_EULER_VALID_MAX

# Processing defaults
NAV_PAD_SECONDS = 60
ER2_PAD_SECONDS = 60
OBPG_DEFAULT_VERSION = "V001"
OBPG_DEFAULT_MISSION = "PACEPAX"
OBPG_DEFAULT_INSTRUMENT = "AH2SWIRR"
OBPG_TIME_FORMAT = "%Y%m%dT%H%M%S"
DEFAULT_REPRESENTATIVE_TEC = 0
DEFAULT_REPRESENTATIVE_INT_TIME_US = 5000
DEFAULT_REPRESENTATIVE_CFC_ID = 0

#----------------------------------------------------------------------------
#-- TIME UTILITY FUNCTIONS
#----------------------------------------------------------------------------

def GetJD(dt_obj):
    """
    Gets the proper julian date since the start of the julian calendar down to
    microsecond resolution.
    
    :param dt_obj: Python datetime object
    :return: Julian date
    """
    t = dt_obj
    jd_j2000 = 2451545.0  # Julian for 1/1/2000
    t -= dt.timedelta(hours=12)  # Julian time is 12 hours lagging behind UTC time
    year = t.year
    nleap = int((year-1-2000)/4+1)
    numdays = nleap*366+365*(year-2000-nleap)
    myjul = jd_j2000+numdays+int(dt.datetime.strftime(t-dt.timedelta(days=1), '%j'))
    myjul += t.hour/24+t.minute/60/24+t.second/3600/24+t.microsecond*1e-6/3600/24
    return myjul


def calculate_seconds(time):
    """
    Convert a Python time object into seconds of day and Julian Day
    
    :param time: Python datetime object
    :return: Tuple of (seconds_of_day, julian_date)
    """
    seconds_of_day = time.hour*3600 + time.minute*60 + time.second + time.microsecond*1e-6
    jdate = GetJD(time)
    return (seconds_of_day, jdate)

#----------------------------------------------------------------------------
#-- FLIGHT DATA PATHS
#----------------------------------------------------------------------------
# flight data parent path to SWIR images
flightData_20240904_SWIR_IMG_DIR = r"/data/archive/ESI/AirHARP2/PACE-PAX_Campaign/PACE-PAX_FlightData_20240904/SWIR"
flightData_20240906_SWIR_IMG_DIR = r"/data/archive/ESI/AirHARP2/PACE-PAX_Campaign/PACE-PAX_FlightData_20240906/SWIR"

# no metadata file
flightData_20240915_SWIR_IMG_DIR = r"/data/archive/ESI/AirHARP2/PACE-PAX_Campaign/PACE-PAX_FlightData_20240915/SWIR"

flightData_20240917_SWIR_IMG_DIR = r"/data/archive/ESI/AirHARP2/PACE-PAX_Campaign/PACE-PAX_FlightData_20240917/SWIR"
flightData_20240919_SWIR_IMG_DIR = r"/data/archive/ESI/AirHARP2/PACE-PAX_Campaign/PACE-PAX_FlightData_20240919/SWIR"
flightData_20240922_SWIR_IMG_DIR = r"/data/archive/ESI/AirHARP2/PACE-PAX_Campaign/PACE-PAX_FlightData_20240922/SWIR"
flightData_20240923_SWIR_IMG_DIR = r"/data/archive/ESI/AirHARP2/PACE-PAX_Campaign/PACE-PAX_FlightData_20240923/SWIR"
flightData_20240926_SWIR_IMG_DIR = r"/data/archive/ESI/AirHARP2/PACE-PAX_Campaign/PACE-PAX_FlightData_20240926/SWIR"
flightData_20240927_SWIR_IMG_DIR = r"/data/archive/ESI/AirHARP2/PACE-PAX_Campaign/PACE-PAX_FlightData_20240927/SWIR"


SWIR_METADATA_DIR  = r"/data/archive/ESI/AirHARP2/PACE-PAX_Campaign/PACE-PAX_FlightData_20240904/SWIR";  # parent path to metadata files
MATCHED_OUTPUT_DIR = r"/data/home/cmarc/SWIR_Projects/SWIR_L1A_Generation/metadata_matcher";  # path to outputed csv containing matched data

# save paths for netCDF4 nc files
nc_files_save_path = r"/data/home/cmarc/SWIR_Projects/SWIR_L1A_Generation/nc_files" # path to save path containing nc files 